"""empty message

Revision ID: 3af601e14526
Revises: 3184fb60f1c2
Create Date: 2023-04-29 20:58:29.905658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3af601e14526"
down_revision = "3184fb60f1c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wallet", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("wallet")

    # ### end Alembic commands ###
