"""empty message

Revision ID: 3f9f95619c56
Revises: a62d26417cf3
Create Date: 2023-05-03 16:55:33.329298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = "3f9f95619c56"
down_revision = "a62d26417cf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_created", sa.DateTime(), nullable=False))
        batch_op.drop_column("date_registered")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "date_registered",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("date_created")

    # ### end Alembic commands ###
