"""empty message

Revision ID: 44f892cfced1
Revises: cec8c5162910
Create Date: 2023-05-24 16:23:42.870237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44f892cfced1"
down_revision = "cec8c5162910"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placedsignals", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placedsignals", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
