"""empty message

Revision ID: a62d26417cf3
Revises: e432c1d24246
Create Date: 2023-05-03 15:27:46.066245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a62d26417cf3"
down_revision = "e432c1d24246"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "api_key",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=250),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "api_secret",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=250),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "api_secret",
            existing_type=sa.String(length=250),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "api_key",
            existing_type=sa.String(length=250),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
