"""empty message

Revision ID: c12f92e30b6d
Revises: 8cc411df4549
Create Date: 2023-04-30 18:33:22.683136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c12f92e30b6d"
down_revision = "8cc411df4549"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "wallet", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "wallet", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###
