name: Build & Deploy

on:

  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Login MySignalApp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            set -e
            
            # Stop MySignalsApp (if running)
            cd MySignalsApp_Server
            sudo supervisorctl stop MySignalsApp

            # Pull latest code changes
            git pull

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Set Flask application entry point
            export FLASK_APP=MySignalsApp

            # Database migrations
            flask db migrate
            flask db upgrade

            # Deactivate virtual environment
            deactivate

            # Navigate back to parent directory
            cd ../

            # Start MySignalsApp using supervisor
            sudo supervisorctl start MySignalsApp

            # Check MySignalsApp status
            sudo supervisorctl status MySignalsApp

            # Success message
            echo 'Deployent successful'
