name: Build & Deploy

on:

  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy MySignalApp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            cd MySignalsApp_Server
            sudo supervisorctl stop MySignalsApp
            git pull
            source venv/bin/activate
            export FLASK_APP=MySignalsApp
            flask db migrate
            flask db upgrade
            deactivate
            cd ../
            sudo supervisorctl start MySignalsApp
            sudo supervisorctl status MySignalsApp
            echo 'Deployent successful'
            
