name: Build & Deploy

on:

  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Login MySignalApp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Stop MySignalsApp (if running)
        run: |
          set -e
          cd MySignalsApp_Server
          sudo supervisorctl stop MySignalsApp

      - name: Pull code changes
        run: |
          git pull

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Flask application entry point
        run: export FLASK_APP=MySignalsApp

      - name: Database migrations
        run: |
          flask db migrate
          flask db upgrade

      - name: Deactivate virtual environment
        run: deactivate

      - name: Navigate back to parent directory
        run: cd ../

      - name: Start MySignalsApp using supervisor
        run: sudo supervisorctl start MySignalsApp

      - name: Check MySignalsApp status
        run: sudo supervisorctl status MySignalsApp

      - name: Deployment successful
        run: echo 'Deployment successful'
