name: Build & Deploy

on:

  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy MySignalApp
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            set -e
            
            echo "Stop MySignalsApp (if running)"
            cd MySignalsApp_Server
            sudo supervisorctl stop MySignalsApp

            echo "Pull latest code changes"
            git pull

            echo "Activate virtual environment"
            source venv/bin/activate

            echo "Install dependencies"
            pip install -r requirements.txt

            echo "Set Flask application entry point"
            export FLASK_APP=MySignalsApp

            echo "Database migrations"
            flask db migrate
            flask db upgrade

            echo "Deactivate virtual environment"
            deactivate

            echo "Navigate back to parent directory"
            cd ../

            echo "Start MySignalsApp using supervisor"
            sudo supervisorctl start MySignalsApp

            echo "Check MySignalsApp status"
            sudo supervisorctl status MySignalsApp

            echo "Success message"
            echo 'Deployment successful'
